pretrained: false
checkpoint: None
mode: train

model:
  model_name: SEGMENTATIONLAMBDAUNET
  use_reconstruction_module: false
  segmentation_module: LambdaUNet
  segmentation_module_input_channels: 3
  segmentation_module_output_channels: 1
  segmentation_module_channels: 32
  segmentation_module_pooling_layers: 5
  segmentation_module_dropout: 0.0
  segmentation_module_query_depth: 16
  segmentation_module_intra_depth: 4
  segmentation_module_receptive_kernel: 3
  segmentation_module_temporal_kernel: 3
  segmentation_module_normalize: true
  segmentation_loss:
    dice: 1.0
  dice_loss_include_background: true  # always set to true if the background is removed
  dice_loss_to_onehot_y: false
  dice_loss_sigmoid: false
  dice_loss_softmax: false
  dice_loss_other_act: none
  dice_loss_squared_pred: false
  dice_loss_jaccard: false
  dice_loss_flatten: false
  dice_loss_reduction: mean_batch
  dice_loss_smooth_nr: 1e-5
  dice_loss_smooth_dr: 1e-5
  dice_loss_batch: true
  dice_metric_include_background: true  # always set to true if the background is removed
  dice_metric_to_onehot_y: false
  dice_metric_sigmoid: false
  dice_metric_softmax: false
  dice_metric_other_act: none
  dice_metric_squared_pred: false
  dice_metric_jaccard: false
  dice_metric_flatten: false
  dice_metric_reduction: mean_batch
  dice_metric_smooth_nr: 1e-5
  dice_metric_smooth_dr: 1e-5
  dice_metric_batch: true
  segmentation_classes_thresholds: [ 0.5 ]
  segmentation_activation: sigmoid
  magnitude_input: true
  coil_dim: None
  coil_combination_method: None
  log_multiple_modalities: true  # log all modalities in the same image, e.g. T1, T2, T1ce, FLAIR will be concatenated
  normalization_type: minmax
  normalize_segmentation_output: false
  unnormalize_loss_inputs: false
  unnormalize_log_outputs: false
  complex_data: false
  consecutive_slices: 3
  dimensionality: 2

  train_ds:
    data_path: data_parent_dir/ISLES2022SubAcuteStroke/preprocessed/folds/fold_0_train.json
    coil_sensitivity_maps_path: None
    mask_path: None
    noise_path: None
    initial_predictions_path: None
    dataset_format: ISLES2022SubAcuteStroke
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 3
    data_saved_per_slice: false
    apply_prewhitening: false
    apply_gcc: false
    estimate_coil_sensitivity_maps: false
    coil_combination_method: None
    dimensionality: 2
    mask_args:
      type: none
    partial_fourier_percentage: 0.0
    remask: false
    crop_size: [ 96, 96 ]
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: minmax
    kspace_normalization: false
    coil_dim: None
    use_seed: false
    segmentations_path: data_parent_dir/ISLES2022SubAcuteStroke/preprocessed/segmentations
    segmentation_classes: 1
    complex_data: false
    batch_size: 1
    shuffle: true
    num_workers: 8
    pin_memory: false
    drop_last: false

  validation_ds:
    data_path: data_parent_dir/ISLES2022SubAcuteStroke/preprocessed/folds/fold_0_val.json
    coil_sensitivity_maps_path: None
    mask_path: None
    noise_path: None
    initial_predictions_path: None
    dataset_format: ISLES2022SubAcuteStroke
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 3
    data_saved_per_slice: false
    complex_target: false
    log_images_rate: 1.0
    apply_prewhitening: false
    apply_gcc: false
    estimate_coil_sensitivity_maps: false
    coil_combination_method: None
    dimensionality: 2
    mask_args:
      type: none
    partial_fourier_percentage: 0.0
    remask: false
    crop_size: [ 96, 96 ]
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: minmax
    kspace_normalization: false
    coil_dim: None
    use_seed: true
    segmentations_path: data_parent_dir/ISLES2022SubAcuteStroke/preprocessed/segmentations/
    segmentation_classes: 1
    complex_data: false
    batch_size: 1
    shuffle: false
    num_workers: 8
    pin_memory: false
    drop_last: false

  optim:
    name: adamw
    lr: 1e-4
    betas:
      - 0.9
      - 0.999
    weight_decay: 1e-5
    sched:
        name: CosineAnnealing
        min_lr: 0.0
        last_epoch: -1
        warmup_ratio: 0.1

trainer:
  strategy: ddp_find_unused_parameters_false
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 50
  precision: 16-mixed  # '16-mixed', 'bf16-mixed', '32-true', '64-true', '64', '32', '16', 'bf16'
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: output_dir/atommic/segmentation/trained_models/ISLES2022SubAcuteStroke/LambdaUNet3D
  ema:
    enable: false
  create_tensorboard_logger: true
  create_wandb_logger: false
