atommic run -c projects/ATOMMIC_paper/MTL/SKMTEA/conf/targets/Test_SENSE.yaml
atommic run -c projects/ATOMMIC_paper/MTL/SKMTEA/conf/test/4x/idslr.yaml
atommic run -c projects/ATOMMIC_paper/MTL/SKMTEA/conf/test/4x/idslrunet.yaml
atommic run -c projects/ATOMMIC_paper/MTL/SKMTEA/conf/test/4x/mtlrs.yaml
atommic run -c projects/ATOMMIC_paper/MTL/SKMTEA/conf/test/4x/segnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/targets/12_channel_Val_RSS.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/ccnn.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/crnn.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/cirim.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/jointicnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/kikinet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/lpdnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/modl.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/rim.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/rvn.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/unet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/varnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/vsnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/xpdnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/5x/zerofilled.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/ccnn.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/crnn.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/cirim.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/jointicnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/kikinet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/lpdnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/modl.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/rim.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/rvn.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/unet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/varnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/vsnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/xpdnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/CC359/conf/test/10x/zerofilled.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/targets/Val_RSS.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/ccnn.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/crnn.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/cirim.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/jointicnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/kikinet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/lpdnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/modl.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/rim.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/rvn.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/unet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/varnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/vsnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/xpdnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/4x/zerofilled.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/ccnn.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/crnn.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/cirim.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/jointicnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/kikinet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/lpdnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/modl.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/rim.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/rvn.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/unet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/varnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/vsnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/xpdnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/fastMRIBrainsMulticoil/conf/test/8x/zerofilled.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/targets/Test_SENSE.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/ccnn.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/cirim.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/jointicnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/kikinet.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/lpdnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/modl.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/rim.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/rvn.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/unet.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/varnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/vsnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/xpdnet.yaml
atommic run -c projects/ATOMMIC_paper/REC/StanfordKnees2019/conf/test/zerofilled.yaml
atommic run -c projects/ATOMMIC_paper/SEG/BraTS2023AdultGlioma/conf/test/attentionunet.yaml
atommic run -c projects/ATOMMIC_paper/SEG/BraTS2023AdultGlioma/conf/test/dynunet.yaml
atommic run -c projects/ATOMMIC_paper/SEG/BraTS2023AdultGlioma/conf/test/unet2d.yaml
atommic run -c projects/ATOMMIC_paper/SEG/BraTS2023AdultGlioma/conf/test/unet3d.yaml
atommic run -c projects/ATOMMIC_paper/SEG/BraTS2023AdultGlioma/conf/test/vnet.yaml
atommic run -c projects/ATOMMIC_paper/SEG/ISLES2022SubAcuteStroke/conf/test/attentionunet.yaml
atommic run -c projects/ATOMMIC_paper/SEG/ISLES2022SubAcuteStroke/conf/test/dynunet.yaml
atommic run -c projects/ATOMMIC_paper/SEG/ISLES2022SubAcuteStroke/conf/test/unet2d.yaml
atommic run -c projects/ATOMMIC_paper/SEG/ISLES2022SubAcuteStroke/conf/test/unet3d.yaml
atommic run -c projects/ATOMMIC_paper/SEG/ISLES2022SubAcuteStroke/conf/test/vnet.yaml
atommic run -c projects/ATOMMIC_paper/SEG/SKMTEA/conf/test/attentionunet.yaml
atommic run -c projects/ATOMMIC_paper/SEG/SKMTEA/conf/test/dynunet.yaml
atommic run -c projects/ATOMMIC_paper/SEG/SKMTEA/conf/test/unet2d.yaml
atommic run -c projects/ATOMMIC_paper/SEG/SKMTEA/conf/test/unet3d.yaml
atommic run -c projects/ATOMMIC_paper/SEG/SKMTEA/conf/test/vnet.yaml
atommic run -c projects/ATOMMIC_paper/qMRI/AHEAD/conf/targets/Test_SENSE.yaml
atommic run -c projects/ATOMMIC_paper/qMRI/AHEAD/conf/reconstruction_test/cirim_test_set.yaml
atommic run -c projects/ATOMMIC_paper/qMRI/AHEAD/conf/reconstruction_test/cirim_train_set.yaml
atommic run -c projects/ATOMMIC_paper/qMRI/AHEAD/conf/reconstruction_test/cirim_val_set.yaml
atommic run -c projects/ATOMMIC_paper/qMRI/AHEAD/conf/reconstruction_test/varnet_test_set.yaml
atommic run -c projects/ATOMMIC_paper/qMRI/AHEAD/conf/reconstruction_test/varnet_train_set.yaml
atommic run -c projects/ATOMMIC_paper/qMRI/AHEAD/conf/reconstruction_test/varnet_val_set.yaml
atommic run -c projects/ATOMMIC_paper/qMRI/AHEAD/conf/quantitative_test/qcirim.yaml
atommic run -c projects/ATOMMIC_paper/qMRI/AHEAD/conf/quantitative_test/qvarnet.yaml
