pretrained: false
checkpoint: None
mode: train

model:
  model_name: CIRIM
  recurrent_layer: IndRNN
  conv_filters:
    - 64
    - 64
    - 2
  conv_kernels:
    - 5
    - 3
    - 3
  conv_dilations:
    - 1
    - 2
    - 1
  conv_bias:
    - true
    - true
    - false
  recurrent_filters:
    - 64
    - 64
    - 0
  recurrent_kernels:
    - 1
    - 1
    - 0
  recurrent_dilations:
    - 1
    - 1
    - 0
  recurrent_bias:
    - true
    - true
    - false
  depth: 2
  time_steps: 8
  conv_dim: 2
  num_cascades: 5
  no_dc: true
  keep_prediction: true
  accumulate_predictions: true
  dimensionality: 2
  reconstruction_loss:
    l1: 1.0
  normalization_type: minmax
  unnormalize_loss_inputs: false
  unnormalize_log_outputs: false
  metric_computation_mode: per_slice  # per_slice: metrics are computed slice-wise and aggregated all together, per_volume: metrics are computed volume-wise and averaged by volume
  kspace_reconstruction_loss: false
  total_reconstruction_loss_weight: 1.0
  complex_valued_type: complex_abs  # stacked, complex_abs, complex_sqrt_abs
  coil_combination_method: RSS
  ssdu: false
  n2r: false
  fft_centered: true
  fft_normalization: ortho
  spatial_dims:
    - -2
    - -1
  coil_dim: 1
  estimate_coil_sensitivity_maps_with_nn: true
  consecutive_slices: 1

  train_ds:
    data_path: data_parent_dir/singlecoil_train
    coil_sensitivity_maps_path: None
    mask_path: None
    noise_path: None
    initial_predictions_path: None
    dataset_format: fastmri
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    complex_target: false
    apply_prewhitening: false
    apply_gcc: false
    estimate_coil_sensitivity_maps: false
    coil_combination_method: RSS
    dimensionality: 2
    mask_args:
      type: random1d
      accelerations:
        - 4
        - 8
      center_fractions:
        - 0.08
        - 0.04
      shift_mask: false
      use_seed: false
    partial_fourier_percentage: 0.0
    remask: false
    ssdu: false
    n2r: false
    unsupervised_masked_target: false
    crop_size: [320, 320]
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: minmax
    kspace_normalization: false
    fft_centered: true
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: false
    batch_size: 1
    shuffle: true
    num_workers: 8
    pin_memory: false
    drop_last: false

  validation_ds:
    data_path: data_parent_dir/singlecoil_val
    coil_sensitivity_maps_path: None
    mask_path: None
    noise_path: None
    initial_predictions_path: None
    dataset_format: fastmri
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    complex_target: false
    log_images_rate: 0.05
    apply_prewhitening: false
    apply_gcc: false
    estimate_coil_sensitivity_maps: false
    coil_combination_method: RSS
    dimensionality: 2
    mask_args:
      type: random1d
      accelerations:
        - 4
        - 8
      center_fractions:
        - 0.08
        - 0.04
      shift_mask: false
      use_seed: true
    partial_fourier_percentage: 0.0
    remask: false
    ssdu: false
    n2r: false
    unsupervised_masked_target: false
    crop_size: [320, 320]
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: minmax
    kspace_normalization: false
    fft_centered: true
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: true
    batch_size: 1
    shuffle: false
    num_workers: 8
    pin_memory: false
    drop_last: false

  optim:
    name: adam
    lr: 1e-4
    betas:
      - 0.9
      - 0.999
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp_find_unused_parameters_false
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 20
  precision: 16-mixed
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: output_dir/atommic/reconstruction/trained_models/fastMRI_Knees_singlecoil_random1d_4x_8x_NNEstimationCSM/CIRIM/
  ema:
    enable: false
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: atommic.reconstruction.trained_models.fastMRI_Knees_singlecoil_random1d_4x_8x_NNEstimationCSM
